name: Docker Image CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * 1'

env:
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  hyperf:
    name: build ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.4'
          - '8.0'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the docker image
      run: |
        docker build -t yansongda/skeleton-hyperf -f ./php-hyperf/php-${{ matrix.php-version }}/Dockerfile ./php-hyperf/php-${{ matrix.php-version }}
    - name: Tag the image
      run: |
        docker tag yansongda/skeleton-hyperf registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:hyperf-${{ matrix.php-version }}
    - name: Push the image to aliyun registry
      run: |
        docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com -p ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}
        docker push registry.cn-shenzhen.aliyuncs.com/yansongda/php-fpm:${{ matrix.php-version }}-${{ matrix.platform }}
