name: Docker Image > php-hyperf

on:
  push:
  schedule:
    - cron: '0 1 * * 1'

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  build:
    name: Build ${{ matrix.php-version }}-${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Recognize tag
        run: |
          platform=$(echo ${{ matrix.platform }} | sed 's/linux\///g')
          tag=$platform'-hyperf-'${{ matrix.php-version }}

          echo $tag
          echo "tag=$tag" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Build the docker image
        run: |
          docker buildx ls
          docker buildx build -t yansongda/skeleton --platform ${{ matrix.platform }} -f ./php-hyperf/php-${{ matrix.php-version }}/Dockerfile ./php-hyperf/php-${{ matrix.php-version }}
      - name: Tag the image
        run: |
          docker tag yansongda/skeleton yansongda/skeleton:$tag
          docker tag yansongda/skeleton registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:$tag
      - name: Push the image to docker registry
        run: |
          echo $DOCKERHUB_TOKEN | docker login --username yansongda --password-stdin
          docker push yansongda/skeleton:$tag
          docker logout
      - name: Push the image to aliyun registry
        run: |
          echo $ALIYUN_IMAGE_TOKEN | docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com --password-stdin
          docker push registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:$tag
          docker logout
  manifest:
    name: Manifest ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
    env:
      PLATFORMS: "linux/arm64 linux/amd64"
    steps:
      - name: Recognize manifest
        run: |
          tag='hyperf-'${{ matrix.php-version }}

          echo $tag
          echo "tag=$tag" >> $GITHUB_ENV
      - name: Tag the manifest
        run: |
          list=$(echo $PLATFORMS | sed 's/linux\///g')

          hub=''
          aliyun=''
          for platform in $list;  
          do  
            hub=$hub'yansongda/skeleton:'$platform'-'$tag' '
            aliyun=$aliyun'registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:'$platform'-'$tag' '
          done

          docker manifest create yansongda/skeleton:$tag $hub
          docker manifest create registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:$tag $aliyun
      - name: Push the manifest to docker registry
        run: |
          echo $DOCKERHUB_TOKEN | docker login --username yansongda --password-stdin
          docker manifest push yansongda/skeleton:$tag
          docker logout
      - name: Push the manifest to aliyun registry
        run: |
          echo $ALIYUN_IMAGE_TOKEN | docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com --password-stdin
          docker manifest push registry.cn-shenzhen.aliyuncs.com/yansongda/skeleton:$tag
          docker logout
